@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

' < ================================================================================================================ > '

package logic #LightBlue
{
    ' < ================================================================================================================ > '
    ' < ================================================================================================================ > '


    package logic.cardLogic #White{

        abstract class CardLogic <<abstract>> {
            - m_name: String
            - m_hp: Integer
            + <<Create>> CardLogic(name: String, hp: Integer)
            + getName(): String
            + getHp(): Integer
            + takeDamage(damage: Integer): Integer
            + isDead(): Boolean
        }

        class ObstacleLogic Extends CardLogic{
            + <<Create>> ObstacleLogic(name: String, hp: Integer)
        }

        class SummonCostLogic {
            - m_blood: Integer
            - m_bones: Integer
            - <<Create>> SummonCostLogic(blood: Integer, bones: Integer)
            + {static} newBloodCost(blood: Integer): SummonCostLogic
            + {static} newBonesCost(bones: Integer): SummonCostLogic
            + {static} newFree(): SummonCostLogic
            + getBlood(): Integer
            + getBones(): Integer
            + isFree(): Boolean
            + isBloodCost(): Boolean
            + isBonesCost(): Boolean
        }

        abstract class AnimalLogic <<abstract>> Extends CardLogic{
            - m_attack: Integer
            + <<Create>> AnimalLogic(name: String, hp: Integer, attack: Integer, cost: SummonCostLogic)
            + <<Create>> AnimalLogic(name: String, hp: Integer, attack: Integer, cost: SummonCostLogic, power: Power)
            + getAttack(): Integer
            + getSummonCost(): SummonCostLogic
            + getPower(): Power
            + hasPower(): Boolean
            + getPowerName(): String
            + attacksDirectly(): Boolean
            + setPower(power: Power)
            + attack(target: CardLogic): Integer
        }

        class FlyingLogic Extends AnimalLogic{
            + <<Create>> FlyingLogic(name: String, hp: Integer, attack: Integer, cost: SummonCostLogic)
            + <<Create>> FlyingLogic(name: String, hp: Integer, attack: Integer, cost: SummonCostLogic, power: Power)
            + attacksDirectly(): Boolean
            + attack(target: CardLogic): Integer
        }

        class TerrestrialLogic Extends AnimalLogic{
            + <<Create>> TerrestrialLogic(name: String, hp: Integer, attack: Integer, summonCostLogic: SummonCostLogic)
            + <<Create>> TerrestrialLogic(name: String, hp: Integer, attack: Integer, cost: SummonCostLogic, power: Power)
        }

        package powers {
            Interface Power <<interface>>{
                + getName(): String
                + onAttack(position: Integer, left: CardLogic, right: CardLogic): Integer
                + onTurnStart(): AnimalLogic
                + onDamageReceived(attacker: AnimalLogic):
                + attackModifierOnFacing(): Integer
                + canDeath(): Boolean
                + killsOnHit(card: CardLogic): Boolean
            }

            class DeadlyContact implements Power{
                + {static} NAME: String
                + <<Create>> DeadlyContact()
                + getName(): String
                + killsOnHit(card: CardLogic): Boolean
            }

            class Growth implements Power{
                - nbTimeOnBord: Integer
                + {static} NAME: String
                + <<Create>> Growth()
                + getName(): String
                + onTurnStart(): AnimalLogic
            }

            class ManyLife implements Power{
                + {static} NAME: String
                + <<Create>> ManyLife()
                + getName(): String
                + canDeath(): Boolean
            }

            class Runner implements Power{
                + {static} NAME: String
                + <<Create>> Runner()
                + getName(): String
                + onAttack(position: Integer, left: CardLogic, right: CardLogic): Integer
            }

            class SharpSpikes implements Power{
                + {static} NAME: String
                + <<Create>> SharpSpikes()
                + getName(): String
                + onDamageReceived(attacker: AnimalLogic):
            }

            class Stinking implements Power{
                + {static} NAME: String
                + <<Create>> Stinking()
                + getName(): String
                + attackModifierOnFacing(): Integer
            }
        }


}

    ' < ================================================================================================================ > '
    ' < ================================================================================================================ > '

    package gameLogic #White
    {
        class GameLogic
        {
            + << Create >> GameLogic()
            + play()
            + offerCard()
        }

        class RoundLogic
        {
            - m_score : Integer
            + << Create >> RoundLogic(cards : CardLogic[])
            + play(player : PlayerLogic, bot : BotLogic)
            + updateScore(newScore : Integer)
            + isWon() : Boolean
            + isEnd() : Boolean
        }

        class TurnLogic
        {
            + << Create >> TurnLogic(gamebord : GameBoardLogic, stack : StackLogic)
            + playerTurn(player : PlayerLogic)
            + botTurn(bot : BotLogic)
            + drawCard(actor : ActorLogic)
            + placeCard(actor : ActorLogic, indexHand : Integer, position : Integer)
            + resolveAttacks(player : PlayerLogic, bot : BotLogic) : Integer
        }

        class GameBoardLogic
        {
            + << Create >> GameBoardLogic()
            + setPlayerLine(card : CardLogic, position : Integer)
            + getPlayerLine(position : Integer) : CardLogic
            + setBotLine(card : CardLogic, position : Integer)
            + getBotLine(position : Integer) : CardLogic
            + setPreviewLine(card : CardLogic, position : Integer)
            + getPreviewLine(position : Integer) : CardLogic
        }

        class StackLogic
        {
            + << Create >> StackLogic(cards : CardLogic[])
            + addCard(card : CardLogic)
            + drawCard() : CardLogic
            + length() : Integer
            + isEmpty() : Boolean
        }
    }

    ' < ================================================================================================================ > '
    ' < ================================================================================================================ > '

    package actorLogic #White
    {
        class ActorLogic
        {
            + {static} PLAYER : String
            + {static} BOT : String
            - m_bones : Integer
            - m_name : String
            + << Create >> ActorLogic(String name)
            + getName() : String
            + addBones(amount : Integer)
            + getBones() : Integer
            + addCard(card : CardLogic)
            + getCard(indexHand : Integer) : CardLogic
            + removeCard(indexHand : Integer) : CardLogic
            + handSize() : Integer
        }
    }
}

    AnimalLogic "1" *--> "1\n-m_summonCostLogic" SummonCostLogic : coûte
    AnimalLogic "1" *---> "0..1\n-m_power\n" Power : est doté d'un

    ActorLogic "1" *--> "0..*\n-m_hand" CardLogic : <<contains>>

    StackLogic "1" o--> "0..16\n-m_cards" CardLogic : <<contains>>

    GameBoardLogic "*" o--> "0..4\n-m_playerLine" CardLogic : <<own>>
    GameBoardLogic "*" o--> "0..4\n-m_botLine" CardLogic : <<own>>
    GameBoardLogic "*" o--> "0..4\n-m_botPreview" CardLogic : <<own>>

    TurnLogic "*" o---> "1\n-m_gameboard" GameBoardLogic : <<own>>
    TurnLogic "*" o---> "1\n-m_stack" StackLogic : <<own>>
    TurnLogic --> ActorLogic : <<uses>>

    RoundLogic "*" o---> "1\n-m_gameboard" GameBoardLogic : <<own>>
    RoundLogic "*" o---> "1\n-m_stack" StackLogic : <<own>>
    RoundLogic --> TurnLogic : <<instantiate>>
    RoundLogic --> ActorLogic : <<uses>>

    GameLogic "*" *--> "3\n-m_rounds" RoundLogic : <<own>>
    GameLogic "1" *---> "1\n-m_player" ActorLogic : <<own>>
    GameLogic "1" *---> "1\n-m_bot" ActorLogic : <<own>>
    GameLogic "*" *---> "12\n-{static}m_baseCard" CardLogic : <<own>>

' < ================================================================================================================ > '

package graphics #LightGreen
{
    package gameGraphics #White
    {
        class ConsoleGrid
        {
            - m_grid : char[][]
            - m_width : Integer
            - m_height : Integer
            + << Create >> ConsoleGrid(width : Integer, height : Integer)
            + writeString(text : String, x : Integer, y : Integer) : void
            + writeBox(width : Integer, height : Integer, x : Integer, y : Integer) : void
            + render() : void
            + clear() : void
        }

        class GameBoardGraphics
        {
            + << Create >> GameBoardGraphics()
            + drawBoard(grid : ConsoleGrid, board : GameBoardLogic, score : Integer, currentTurn : Integer, currentMatch : Integer) : void
        }

        class TurnGraphics
        {
            + << Create >> TurnGraphics()
            + displayFullTurn(board : GameBoardLogic, player : PlayerLogic, stack : StackLogic, score : Integer, turn : Integer, match : Integer) : void
        }

        class MenuGraphics
        {
            + << Create >> MenuGraphics()
            + drawStartMenu(grid : ConsoleGrid) : void
            + drawEndMenu(grid : ConsoleGrid, score : Integer) : void
        }
    }

    package cardGraphics #White
    {
        class CardGraphics
        {
            + << Create >> CardGraphics()
            + drawCard(grid : ConsoleGrid, card : CardLogic, x : Integer, y : Integer) : void
            + drawEmpty(grid : ConsoleGrid, x : Integer, y : Integer) : void
        }
    }
}

    TurnGraphics ..> ConsoleGrid : <<instantiate>>
    GameBoardGraphics ..> ConsoleGrid : <<uses>>
    CardGraphics ..> ConsoleGrid : <<uses>>
    MenuGraphics ..> ConsoleGrid : <<uses>>

    TurnGraphics "1" *---> "1" GameBoardGraphics : <<uses>>
    GameBoardGraphics "1" *---> "1" CardGraphics : <<uses>>

' < ================================================================================================================ > '

    CardGraphics ..> CardLogic : <<uses>>
    GameBoardGraphics ..> GameBoardLogic : <<uses>>

    TurnGraphics ..> GameBoardLogic : <<uses>>
    TurnGraphics ..> ActorLogic : <<uses>>
    TurnGraphics ..> StackLogic : <<uses>>

    TurnLogic ..> TurnGraphics : <<uses>>
    GameLogic ..> MenuGraphics : <<uses>>

' < ================================================================================================================ > '
@enduml